# gitpod.io/#github.com/CaravanaCloud/okd-pod
image:
  file: .gitpod.Dockerfile

tasks:
  - name: shell
    command: echo "Welcome to okd-pod :)"

ports:
  - port: 3300
    onOpen: ignore
    visibility: public

  - port: 3306
    onOpen: ignore
    visibility: public

  - port: 5000
    onOpen: ignore
    visibility: public

  - port: 5005
    onOpen: ignore
    visibility: public

  - port: 8080
    onOpen: ignore
    visibility: public

  - port: 8081
    onOpen: open-browser
    visibility: public

  - port: 8888
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.vscode-openshift-connector
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode
