name: Create OKD Cluster on AWS (temporary)

on:
  workflow_dispatch:
    inputs:
      env_id:
        description: 'Environment ID'
        required: true
        default: 'okdpod'

jobs:
  create-okd-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.REDHACKS_TEMP_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.REDHACKS_TEMP_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Check AWS auth
      run: aws sts get-caller-identity
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install openshift installer 
      env:
        REPO_URL: "https://github.com/okd-project/okd/releases/download"
        RELEASE_TAG: "4.14.0-0.okd-2023-12-01-225814"
        RELEASE_PKG: "openshift-install-linux-4.14.0-0.okd-2023-12-01-225814.tar.gz"
        INSTALL_URL: "https://github.com/okd-project/okd/releases/download/4.14.0-0.okd-2023-12-01-225814/openshift-install-linux-4.14.0-0.okd-2023-12-01-225814.tar.gz"
        TEMP_DIR: "/tmp/openshift-install"
        TEMP_FILE: "openshift-install-linux.tar.gz"        
      run: |
        mkdir -p "${TEMP_DIR}" \
        && wget -nv -O "${TEMP_DIR}/${TEMP_FILE}" "${INSTALL_URL}" \
        && tar zxvf "${TEMP_DIR}/${TEMP_FILE}" -C "${TEMP_DIR}" \
        && sudo mv  "${TEMP_DIR}/openshift-install" "/usr/local/bin/" \    
        && rm "${TEMP_DIR}/${TEMP_FILE}" \
        && openshift-install version

