name: Create OKD Cluster on AWS (temporary)

on:
  workflow_dispatch:
    inputs:
      env_id:
        description: 'Environment ID'
        required: true
        default: 'okdpod'

jobs:
  create-okd-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.REDHACKS_TEMP_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.REDHACKS_TEMP_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Check AWS auth
      run: aws sts get-caller-identity
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install openshift installer 
      env:
        INSTALL_URL: "https://github.com/okd-project/okd/releases/download/4.14.0-0.okd-2023-12-01-225814/openshift-install-linux-4.14.0-0.okd-2023-12-01-225814.tar.gz"        
      run: |
        mkdir -p "/tmp/openshift-install" \
        && wget -nv -O "/tmp/openshift-install/openshift-install-linux.tar.gz" "${INSTALL_URL}" \
        && tar zxvf "/tmp/openshift-install/openshift-install-linux.tar.gz" -C "/tmp/openshift-install" \
        && rm "/tmp/openshift-install/openshift-install-linux.tar.gz" \
    
    - name: Check openshift installer
      run: /tmp/openshift-install/openshift-install version

